### ISSUE TITLE
example dplyr spatial join fails with by can't contain join column

### ISSUE THREAD

**Issue by geoHeil** [harryprince/geospark#9]
Note, https://github.com/tidyverse/dplyr/releases only contains dplyr 0.8.0.1 not 0.9

so 
You can also perform this query using dplyr 0.9 installed through:

```
remotes::install_github("tidyverse/dplyr")
remotes::install_github("tidyverse/dbplyr")
```
will also only install 0.8 and not 0.9. In case this is a typo: sparklyR can now be installed in 1.0.0 from CRAN.

This might be related to the issue:

```
polygons_wkt <- mutate(polygons_wkt, poly = st_geomfromwkt(geom, "4326"))
points_wkt <- mutate(points_wkt, point = st_geomfromwkt(geom, "4326"))

sc_res = inner_join(polygons_wkt, points_wkt, by = sql("st_contains(poly, point)")) %>% 
  group_by(area, state) %>%
  summarise(cnt = n())
  
sc_res %>%
  head()
```

fails with:
``by` can't contain join column `st_contains(poly, point)` which is missing from LHS`

**Comment by harryprince** [comment]
`dplyr` currently does not support `inequal join`, in that, we need to use `dummy` join trick.

```
full_join(polygons_wkt  %>% mutate(dummy=TRUE),
          points_wkt %>% mutate(dummy=TRUE),
          by = "dummy") %>% 
   filter(sql("st_contains(y,x)")) %>%
  group_by(area, state) %>%
  summarise(cnt = n()) 
```

**Comment by harryprince** [comment]
see harryprince/geospark#10

**Comment by geoHeil** [comment]
Interesting, this interprets fine on R but fails in spark:
`Detected implicit cartesian product for FULL OUTER join between `. I know it would be possible to enable the Cartesian product, but why are Geospark Range Join Catalyst optimisations not loaded? Shouldn't they prevent the Cartesian product?

**Comment by harryprince** [comment]
```
res = full_join(polygons_wkt %>% mutate(x = st_geomfromwkt(geom)) %>% mutate(dummy_s4pu629cnd=TRUE) %>% compute("x"),
          points_wkt %>% mutate(y = st_geomfromwkt(geom)) %>% mutate(dummy_s4pu629cnd=TRUE) %>% compute("y"),
          by = "dummy_s4pu629cnd") %>%
    filter(sql("st_contains(x,y)")) %>% 
    select(-dummy_s4pu629cnd)
```





```
dbplyr::sql_render(res)
```


```
SELECT `area`, `geom.x`, `x`, `city`, `state`, `geom.y`, `y`
FROM (SELECT *
FROM (SELECT `TBL_LEFT`.`area` AS `area`, `TBL_LEFT`.`geom` AS `geom.x`, `TBL_LEFT`.`x` AS `x`, coalesce(`TBL_LEFT`.`dummy_s4pu629cnd`, `TBL_RIGHT`.`dummy_s4pu629cnd`) AS `dummy_s4pu629cnd`, `TBL_RIGHT`.`city` AS `city`, `TBL_RIGHT`.`state` AS `state`, `TBL_RIGHT`.`geom` AS `geom.y`, `TBL_RIGHT`.`y` AS `y`
  FROM `x` AS `TBL_LEFT`
  FULL JOIN `y` AS `TBL_RIGHT`
  ON (`TBL_LEFT`.`dummy_s4pu629cnd` = `TBL_RIGHT`.`dummy_s4pu629cnd`)
) `zabkzkflwc`
WHERE (st_contains(x,y))) `npqtohnpkb`
```

**Comment by harryprince** [comment]
relate issue:
https://github.com/tidyverse/dbplyr/pull/146

**Comment by geoHeil** [comment]
Even when setting `conf$`spark.sql.crossJoin.enabled` <- "true"`
`Exception thrown in awaitResult`
see https://gist.github.com/geoHeil/bec24156ae2485144d467386d19384ca for details

**Comment by geoHeil** [comment]
And your updated code of:
```
res = full_join(polygons_wkt %>% 
                        mutate(x = st_geomfromwkt(geom)) %>%
                        mutate(dummy_s4pu629cnd=TRUE) %>% 
                        compute("x"),
               points_wkt %>% 
                        mutate(y = st_geomfromwkt(geom)) %>% 
                        mutate(dummy_s4pu629cnd=TRUE) %>% 
                        compute("y"),
          by = "dummy_s4pu629cnd") %>%
    filter(sql("st_contains(x,y)")) %>% 
    select(-dummy_s4pu629cnd)
```

fails with `java.lang.AssertionError: assertion failed`: https://gist.github.com/geoHeil/22a10d33bf75054d7165958718e80ca6

regardless of cross join is enabled.

**Comment by geoHeil** [comment]
But also for `2.3.2` the same error persists: `java.lang.AssertionError: assertion failed`

**Comment by harryprince** [comment]
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] dbplyr_1.2.1     raster_2.7-15   
[3] sp_1.3-1         knitr_1.22      
[5] testthat_2.0.1   dplyr_0.8.0.9014
[7] sparklyr_1.0.0   geospark_0.0.2  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1          lattice_0.20-35    
 [3] forge_0.2.0         png_0.1-7          
 [5] class_7.3-14        assertthat_0.2.1   
 [7] rprojroot_1.3-2     digest_0.6.18      
 [9] packrat_0.5.0       utf8_1.1.4         
[11] mime_0.6            R6_2.4.0           
[13] backports_1.1.3     stats4_3.4.3       
[15] evaluate_0.13       e1071_1.7-0.1      
[17] httr_1.4.0          ggplot2_3.1.0.9000 
[19] highr_0.6           pillar_1.3.1       
[21] rlang_0.3.4.9000    lazyeval_0.2.1.9000
[23] rstudioapi_0.9.0    config_0.3         
[25] desc_1.2.0          webshot_0.5.0      
[27] rgdal_1.3-6         r2d3_0.2.3         
[29] htmlwidgets_1.3     munsell_0.5.0      
[31] shiny_1.2.0         httpuv_1.4.5.1     
[33] compiler_3.4.3      xfun_0.6           
[35] rstan_2.17.3        pkgconfig_2.0.2    
[37] askpass_1.1         base64enc_0.1-3    
[39] htmltools_0.3.6     openssl_1.2.1      
[41] tidyselect_0.2.5    tibble_2.1.1       
[43] gridExtra_2.3       codetools_0.2-15   
[45] mapview_2.6.3       viridisLite_0.3.0  
[47] fansi_0.4.0         later_0.7.5        
[49] crayon_1.3.4        withr_2.1.2.9000   
[51] sf_0.7-2            rappdirs_0.3.1     
[53] grid_3.4.3          satellite_1.0.1    
[55] xtable_1.8-3        jsonlite_1.6       
[57] gtable_0.2.0        DBI_1.0.0.9001     
[59] magrittr_1.5        units_0.6-2        
[61] StanHeaders_2.17.2  scales_1.0.0       
[63] geohash_0.1.2       cli_1.1.0          
[65] promises_1.0.1      leaflet_2.0.2      
[67] ellipsis_0.1.0      generics_0.0.2     
[69] tools_3.4.3         glue_1.3.1         
[71] purrr_0.3.2         crosstalk_1.0.0    
[73] pkgload_1.0.2       parallel_3.4.3     
[75] yaml_2.2.0          inline_0.3.14      
[77] colorspace_1.3-2    classInt_0.3-1  
```

spark_version:
```
spark 2.2
```

**Comment by geoHeil** [comment]
For spark `2.2.1` I still get the same exception.
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin18.2.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.5/lib/libopenblasp-r0.3.5.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.6.3    sf_0.7-3         ggplot2_3.1.1    dplyr_0.8.0.9014
[5] geospark_0.0.2   sparklyr_1.0.0  

loaded via a namespace (and not attached):
 [1] httr_1.4.0         viridisLite_0.3.0  jsonlite_1.6       StanHeaders_2.18.1
 [5] shiny_1.3.0        assertthat_0.2.1   askpass_1.1        sp_1.3-1          
 [9] stats4_3.5.3       yaml_2.2.0         r2d3_0.2.3         pillar_1.3.1      
[13] backports_1.1.3    lattice_0.20-38    glue_1.3.1         digest_0.6.18     
[17] RColorBrewer_1.1-2 promises_1.0.1     colorspace_1.4-1   htmltools_0.3.6   
[21] httpuv_1.5.1       plyr_1.8.4         pkgconfig_2.0.2    rstan_2.18.2      
[25] raster_2.8-19      config_0.3         purrr_0.3.2        xtable_1.8-3      
[29] webshot_0.5.1      scales_1.0.0       processx_3.3.0     satellite_1.0.1   
[33] later_0.8.0        tibble_2.1.1       openssl_1.3        generics_0.0.2    
[37] ellipsis_0.1.0     withr_2.1.2        lazyeval_0.2.2     cli_1.1.0         
[41] magrittr_1.5       crayon_1.3.4       mime_0.6           evaluate_0.13     
[45] ps_1.3.0           class_7.3-15       pkgbuild_1.0.3     tools_3.5.3       
[49] loo_2.1.0          prettyunits_1.0.2  matrixStats_0.54.0 stringr_1.4.0     
[53] munsell_0.5.0      callr_3.2.0        packrat_0.5.0      compiler_3.5.3    
[57] e1071_1.7-1        forge_0.2.0        rlang_0.3.4        classInt_0.3-1    
[61] units_0.6-2        grid_3.5.3         rstudioapi_0.10    rappdirs_0.3.1    
[65] htmlwidgets_1.3    crosstalk_1.0.0    base64enc_0.1-3    rmarkdown_1.12    
[69] gtable_0.3.0       codetools_0.2-16   inline_0.3.15      DBI_1.0.0         
[73] curl_3.3           R6_2.4.0           gridExtra_2.3      knitr_1.22        
[77] rprojroot_1.3-2    stringi_1.4.3      parallel_3.5.3     Rcpp_1.0.1        
[81] png_0.1-7          leaflet_2.0.2      dbplyr_1.3.0.9000  tidyselect_0.2.5  
[85] xfun_0.6          
```

**Comment by harryprince** [comment]
@geoHeil maybe provide your full reproducible example by `reprex` R package is a good option. And I will try it again.

**Comment by geoHeil** [comment]
@harryprince, unfortunately, this also does not work / throws the same error. Please find attached an `reprex` example:

```R
library(sparklyr)
library(geospark)
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"
#conf$`spark.sql.crossJoin.enabled` <- "true"
# Enable kryo to decrease serialization overhead
conf$spark.serializer <- "org.apache.spark.serializer.KryoSerializer"
conf$spark.kryo.registrator <- "org.datasyslab.geospark.serde.GeoSparkKryoRegistrator"

spark <- spark_connect(master = "local", config = conf, version = "2.2.1")
#> Warning in normalizePath(unlist(unique(all_jars))): path[3]="": No such
#> file or directory
register_gis(spark)

polygons <- read.table(system.file(package="geospark","examples/polygons.txt"), sep="|", col.names=c("area","geom"))
points <- read.table(system.file(package="geospark","examples/points.txt"), sep="|", col.names=c("city","state","geom"))

polygons_wkt <- copy_to(spark, polygons)
points_wkt <- copy_to(spark, points)

polygons_wkt <- mutate(polygons_wkt, poly = st_geomfromwkt(geom, "4326"))
points_wkt <- mutate(points_wkt, point = st_geomfromwkt(geom, "4326"))

st_join <- function(x, y, join = NULL) {
  full_join(x %>% mutate(dummy_s4pu629cnd=TRUE) %>% compute(),
            y %>% mutate(dummy_s4pu629cnd=TRUE) %>% compute(),
            by = "dummy_s4pu629cnd") %>% 
    filter(join) %>%
    select(-dummy_s4pu629cnd)
}
res = st_join(polygons_wkt, points_wkt)
#> Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 10.0 failed 1 times, most recent failure: Lost task 0.0 in stage 10.0 (TID 10, localhost, executor driver): java.lang.AssertionError: assertion failed
#>  at scala.Predef$.assert(Predef.scala:156)
#>  at org.apache.spark.sql.geosparksql.expressions.ST_GeomFromWKT.eval(Constructors.scala:123)
#>  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply_0$(Unknown Source)
#>  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
#>  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
#>  at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
#>  at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:102)
#>  at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:92)
#>  at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
#>  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
#>  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
#>  at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
#>  at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
#>  at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
#>  at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
#>  at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
#>  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
#>  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
#>  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
#>  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
#>  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
#>  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
#>  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
#>  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
#>  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
#>  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
#>  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
#>  at org.apache.spark.scheduler.Task.run(Task.scala:108)
#>  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
#>  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
#>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
#>  at java.lang.Thread.run(Thread.java:748)
#> 
#> Driver stacktrace:
#>  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
#>  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
#>  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2094)
#>  at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
#>  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
#>  at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
#>  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:278)
#>  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2435)
#>  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2434)
#>  at org.apache.spark.sql.Dataset$$anonfun$55.apply(Dataset.scala:2842)
#>  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
#>  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2841)
#>  at org.apache.spark.sql.Dataset.count(Dataset.scala:2434)
#>  at org.apache.spark.sql.execution.command.CacheTableCommand.run(cache.scala:45)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:67)
#>  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:183)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:68)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:632)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:498)
#>  at sparklyr.Invoke.invoke(invoke.scala:139)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:13
res
#> Error in eval(expr, envir, enclos): Objekt 'res' nicht gefunden
Created on 2019-04-14 by the reprex package (v0.2.1)
```

**Comment by harryprince** [comment]
>@harryprince, unfortunately, this also does not work / throws the same error. Please find attached an `reprex` example: ...

@geoHeil as the error says, you should use st_geomfromwkt（geom）without explicit 4326 parameter

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geoHeil** [comment]
@harryprince great. This means that I am one step closer:
```
Fehler: org.apache.spark.sql.AnalysisException: cannot resolve '`geom.x`' given input columns: [dbplyr_051.geom.x, dbplyr_051.x, dbplyr_051.dummy_s4pu629cnd, dbplyr_051.geom.y, dbplyr_051.state, dbplyr_051.y, dbplyr_051.city, dbplyr_051.area]; line 2 pos 21;
```
But x,y are present when looking at the input dataframes. This seems strange.

for this code:
```
devtools::install_github("harryprince/geospark")
library(sparklyr)
library(geospark)
library(dplyr)
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"
#conf$`spark.sql.crossJoin.enabled` <- "true"
# Enable kryo to decrease serialization overhead
conf$spark.serializer <- "org.apache.spark.serializer.KryoSerializer"
conf$spark.kryo.registrator <- "org.datasyslab.geospark.serde.GeoSparkKryoRegistrator"

spark <- spark_connect(master = "local", config = conf)
register_gis(spark)

polygons <- read.table(system.file(package="geospark","examples/polygons.txt"), sep="|", col.names=c("area","geom"))
points <- read.table(system.file(package="geospark","examples/points.txt"), sep="|", col.names=c("city","state","geom"))

polygons_wkt <- copy_to(spark, polygons, overwrite = TRUE)
points_wkt <- copy_to(spark, points, overwrite = TRUE)

polygons_wkt <- mutate(polygons_wkt, y = st_geomfromwkt(geom))
points_wkt <- mutate(points_wkt, x = st_geomfromwkt(geom))
points_wkt # y is here
polygons_wkt # x is here
sc_res <- st_join(polygons_wkt,
                  points_wkt,
                  join = sql("st_contains(y,x)")) %>% 
  group_by(area, state) %>%
  summarise(cnt = n()) 

sc_res %>%
  head
spark_disconnect(spark)

```

**Comment by harryprince** [comment]
>@harryprince great. This means that I am one step closer: ...

@geoHeil after mutate function, you need to call compute to cut spark DAG leanage, see st_join
 function


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by harryprince** [comment]
sorry it is my fault, correct code is 

```
sc_res <- st_join(polygons_wkt, points_wkt, join = sql("st_contains(y,x)")) %>%
group_by(area, state) %>%
    summarise(cnt = n()) 
```

**Comment by geoHeil** [comment]
No problem. However,
```
Fehler: org.apache.spark.sql.AnalysisException: cannot resolve '`geom.x`' given input columns: [dbplyr_006.state, dbplyr_006.geom.x, dbplyr_006.area, dbplyr_006.dummy_s4pu629cnd, dbplyr_006.y, dbplyr_006.geom.y, dbplyr_006.x, dbplyr_006.city]; line 2 pos 21;
```
remains unsolved. Even though `st_join` calls out to compute.

**Comment by harryprince** [comment]
@geoHeil please drop `geom` column before st_join, currently, `st_join` not support auto `suffix`.

```
sc_res <- st_join(polygons_wkt %>% select(area,y),
 points_wkt %>% select(city,state,x), join = sql("st_contains(y,x)")) %>%
group_by(area, state) %>%
    summarise(cnt = n()) 
```

**Comment by geoHeil** [comment]
Great now the basics work - almost.
I can now run the example just fine. However:
<img width="621" alt="sparklyr_-_Details_for_Query_51" src="https://user-images.githubusercontent.com/1694964/56191298-66bcfd80-602c-11e9-9679-68949158b4b8.png">
the geospark `RangeJoin` is not applied. Which most likely means this will not really scale out. Do you know why?

**Comment by harryprince** [comment]
Congratulations! 
in `dbplyr`, full_join + filter == inner join.

**Comment by geoHeil** [comment]
Geospark anyhow only supports an `INNER` join. But the SQL which is generated by dbplyr results in an issue for large datasets i.e. the range join optimization is not used.
Only:
![image001](https://user-images.githubusercontent.com/1694964/56198308-f8cc0280-603a-11e9-864b-2fc8e5d42c52.png)
the geospark catalyst optimized range join (which semantically currently only is an INNER JOIN) is efficient.

**Comment by harryprince** [comment]
@geoHeil
if dbplyr can not auto optimize, we can implement by invoke functions too 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geoHeil** [comment]
Certainly they run well - but most likely your datasets are fairly small? Which sizes are you using?

What is `sparklyr::invoke_* ` - could you explain this in more detail? As a workaround could dbplyr execute hand-coded SQL? Do you mean we could run some hand-coded snippets via invoke?

Regarding `range-join` https://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Optimizer/ contains the details.

**Comment by harryprince** [comment]
>Certainly they run well - but most likely your datasets are fairly small? Which sizes are you using? ...

@geoHeil invoke functions can execute scala code directly

dbplyr can execute sql like this 

mutate（sdf，sql（“cast（a as double）”））

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geoHeil** [comment]
executing custom java/scala code is not necessary. 
Geospark operates nicely via SQL: https://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Optimizer/

so basically one would need to hand-code:
```sql
SELECT *
FROM polygondf, pointdf
WHERE ST_Contains(polygondf.polygonshape,pointdf.pointshape)
```

which most likely would look similar to:
```r
sdf_sql(spark, "SELECT * FROM points_wkt a, polygons_wkt b WHERE ST_Intersects(b.geom, a.geom)") ## 
```
in sparklyR.

However, it fails with: `ClassCastException: org.apache.spark.unsafe.types.UTF8String cannot be cast to org.apache.spark.sql.catalyst.util.ArrayData`

Full example:
```R
library(sparklyr)
library(geospark)
library(dplyr)
library(ggplot2)
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"

conf$spark.serializer <- "org.apache.spark.serializer.KryoSerializer"
conf$spark.kryo.registrator <- "org.datasyslab.geospark.serde.GeoSparkKryoRegistrator"

spark <- spark_connect(master = "local", config = conf)
register_gis(spark)

polygons <- read.table(system.file(package="geospark","examples/polygons.txt"), sep="|", col.names=c("area","geom"))
points <- read.table(system.file(package="geospark","examples/points.txt"), sep="|", col.names=c("city","state","geom"))

polygons_wkt <- copy_to(spark, polygons)
points_wkt <- copy_to(spark, points)

polygons_wkt <- mutate(polygons_wkt, y = st_geomfromwkt(geom))
points_wkt <- mutate(points_wkt, x = st_geomfromwkt(geom))


# This fails with the mentioned problem
sdf_sql(spark, "SELECT * FROM points a, polygons b WHERE ST_Intersects(b.geom, a.geom)") ## 

sdf_register(points_wkt, "points_wkt")
sdf_register(polygons_wkt, "polygons_wkt")

# this fails again with the same problem.
sdf_sql(spark, "SELECT * FROM points_wkt a, polygons_wkt b WHERE ST_Intersects(b.geom, a.geom)") ## 
```

**Comment by harryprince** [comment]
>executing custom java/scala code is not necessary.  ...

@geoHeil as you can see from geospark R package exmaple in SQL mode, your syntax is wrong

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geoHeil** [comment]
I would argue it is not wrong. As 
```
polygons_wkt <- mutate(polygons_wkt, y = st_geomfromwkt(geom))
points_wkt <- mutate(points_wkt, x = st_geomfromwkt(geom))

```
already has executed  `st_geomfromwkt `

when accessing the table:
```
df_register(points_wkt, "points_wkt")
sdf_register(polygons_wkt, "polygons_wkt"
```

after execution, I would assume that the transformation actually took place.
Certainly, one could run the whole analytics in SQL mode, but this again is not ideal, i.e. people with an R background would want to stick to dplyr / dbplyr as long as possible and move to SQL only if this is not sufficient.

@harryprince  your suggested SQL seems to be a way to complex considering that you manually call the  `st_geomfromwkt` (which I believe is wrong as it should already have happened). Am I misunderstanding something here?

Anyhow, I would suggest this SQL snippet if it really needs to be coded up from the beginning:
```R
library(sparklyr)
library(geospark)
library(dplyr)
library(ggplot2)
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"

conf$spark.serializer <- "org.apache.spark.serializer.KryoSerializer"
conf$spark.kryo.registrator <- "org.datasyslab.geospark.serde.GeoSparkKryoRegistrator"

spark <- spark_connect(master = "local", config = conf)
register_gis(spark)

polygons <- read.table(system.file(package="geospark","examples/polygons.txt"), sep="|", col.names=c("area","geom"))
points <- read.table(system.file(package="geospark","examples/points.txt"), sep="|", col.names=c("city","state","geom"))

polygons_wkt <- copy_to(spark, polygons)
points_wkt <- copy_to(spark, points)

points_wkt %>% rename(point_geom = geom) %>% sdf_register("point_geom")
sdf_sql(spark, "SELECT * FROM point_geom, polygons WHERE ST_Intersects(ST_geomFromWKT(geom), ST_geomFromWKT(point_geom))")
```

Which nicely operates on a range join:
<img width="417" alt="sparklyr_-_Details_for_Query_33" src="https://user-images.githubusercontent.com/1694964/56343113-2f7c5700-61ba-11e9-9ffd-19347f30bd3c.png">

Still @harryprince this seems clumsy given that initially the data frame was already processed through.  `ST_geomFromWKT` so why do I manually need to call it again?

**Comment by geoHeil** [comment]
And indeed,
```r
mutate(polygons_wkt, y = st_geomfromwkt(geom)) %>%
  select(-geom)%>%
  sdf_register("poly_geometry")
mutate(points_wkt, x = st_geomfromwkt(geom)) %>%
  select(-geom) %>%
  sdf_register("point_geometry")

sdf_sql(spark, "SELECT * FROM poly_geometry, point_geometry WHERE ST_Intersects(y, x)")
```
is possible and in my opinion better and simpler.

**Comment by geoHeil** [comment]
What do you think about updating the example as well as introducing a function which makes even writing:
```
sdf_sql(spark, "SELECT * FROM poly_geometry, point_geometry WHERE ST_Intersects(y, x)")
```
better handled  and simpler for the user?

**Comment by harryprince** [comment]
1. in my example, `ST_geomFromWKT ` only called once, not twice.
2. `sdf_sql` is not general enough than `dplyr::tbl`, when the connection engine change.
3. I think the latest code example is pretty clear.

```
SELECT * FROM poly_geometry, point_geometry WHERE ST_Intersects(y, x)
```

this SQL will push down to inner join automatically, and the current implementation `st_join` do the same thing:

```
st_join(poly_geometry, point_geometry,join=sql("ST_Intersects(y, x)"))
```

**Comment by geoHeil** [comment]
Indeed. But only now the range join optimization for the inner join is
active.



HarryZhu <notifications@github.com> schrieb am Fr. 19. Apr. 2019 um 00:31:
